spring: 
  profiles:
    active:
    - dev
--- 
server:
  port: 8001
spring: 
   profiles: dev
   application: 
       name: springcloud-config-dept-client
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
      url: jdbc:mysql://192.168.216.128:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
## url: jdbc:mysql://192.168.216.128:3306/springcloud              # 数据库名称
      password: Root123!
      dbcp2:
         min-idle: 5 # 数据库连接池的最小维持连接数
         initial-size: 5 # 初始化连接数
         max-total: 5 # 最大连接数
         max-wait-millis: 200 # 等待连接获取的最大超时时间
mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
   type-aliases-package: com.wang.entity # 所有Entity别名类所在包
   mapper-locations:
   - classpath:mybatis/mapper/**/*.xml # mapper映射文件
 
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 
info:
  app.name: wang-springcloud-springcloudconfig01
  company.name: www.wang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring: 
   profiles: test
    application: 
       name: springcloud-config-dept-client
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
      url: jdbc:mysql://192.168.216.128:3306/springcloud1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
## url: jdbc:mysql://192.168.216.128:3306/springcloud              # 数据库名称
      password: Root123!
      dbcp2:
         min-idle: 5 # 数据库连接池的最小维持连接数
         initial-size: 5 # 初始化连接数
         max-total: 5 # 最大连接数
         max-wait-millis: 200 # 等待连接获取的最大超时时间
  
  
mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
   type-aliases-package: com.wang.entity # 所有Entity别名类所在包
   mapper-locations:
   - classpath:mybatis/mapper/**/*.xml # mapper映射文件
 
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
 
info:
  app.name: springcloud-springcloudconfig02
  company.name: www.wang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

